name: flutter_rfid
description: A Flutter plugin that provides integration with RFID readers on iOS platforms, enabling Flutter applications to communicate with RFID tags.
version: 0.0.1
repository: https://github.com/ahfs-hamburg/flutter_rfid
issue_tracker: https://github.com/ahfs-hamburg/flutter_rfid/issues

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  dart_des: ^1.0.2
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterRfidPlugin

topics:
  - rfid
  - nfc
  - ios
  - usb
